debian/minidlna.init: Rewrite init script. (Based on one from dh_make.)
Signed-off-by: Alexander GQ Gerasiov <gq@cs.msu.su>

diff --git a/debian/minidlna.init b/debian/minidlna.init
--- a/debian/minidlna.init
+++ b/debian/minidlna.init
@@ -1,76 +1,50 @@
 #!/bin/sh
-#
-# MiniDLNA initscript
-#
-# Based on the mediatomb debian package.
-# Original authors: Tor Krill <tor@excito.com>
-#                   Leonhard Wimmer <leo@mediatomb.cc>
-#                   Andres Mejia <mcitadel@gmail.com>
-#
-# Modified by: Benoît Knecht <benoit.knecht@fsfe.org>
-#
 ### BEGIN INIT INFO
 # Provides:          minidlna
-# Required-Start:    $network $local_fs $remote_fs
-# Required-Stop::    $network $local_fs $remote_fs
-# Should-Start:      $all
-# Should-Stop:       $all
+# Required-Start:    $local_fs $network $remote_fs
+# Required-Stop:     $local_fs $network $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Start minidlna at boot time
-# Description:       Manage the minidlna daemon, a DLNA/UPnP-AV media server.
+# Short-Description: minidlna server
+# Description:       minidlna, DLNA/UPnP-AV media server.
 ### END INIT INFO
 
-unset USER
+# Authors: Alexander GQ Gerasiov <gq@debian.org>
+#	   Benoît Knecht <benoit.knecht@fsfe.org>
+
+# Do NOT "set -e"
 
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="DLNA/UPnP-AV media server"
 NAME=minidlna
-DAEMON=/usr/bin/minidlnad
+DAEMON=/usr/sbin/minidlnad
 PIDDIR=/run/$NAME
 PIDFILE=$PIDDIR/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
-DEFAULT=/etc/default/$NAME
+
+# Defaults (could be overridden in /etc/default/$NAME)
+CONFIGFILE=/etc/minidlna.conf
+LOGFILE=/var/log/minidlna.log
+USER=minidlna
+GROUP=minidlna
+DAEMON_OPTS=""
 
 # Exit if the package is not installed
-[ -x $DAEMON ] || exit 0
+[ -x "$DAEMON" ] || exit 0
 
 # Read configuration variable file if it is present
-[ -r $DEFAULT ] && . $DEFAULT
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
-. /lib/lsb/init-functions
-
-# Do not start the daemon if NO_START is enabled in DEFAULT
-if [ "$START_DAEMON" != "yes" ] && [ "$1" != "stop" ]; then
-	log_warning_msg "$NAME: Not starting $DESC."
-	log_warning_msg "$NAME: Disabled in $DEFAULT."
-	exit 0
-fi
-
-# Set the default configuration file
-if [ -z $CONFIGFILE ]; then
-	CONFIGFILE=/etc/minidlna.conf
-fi
-
-# Set the default log file
-if [ -z $LOGFILE ]; then
-	LOGFILE=/var/log/minidlna.log
-fi
-
-# Run as `minidlna' if USER is not specified or is `root'
-if [ -z $USER ]; then
-	USER=minidlna
-fi
-
-# If no group is specified, use USER
-if [ -z $GROUP ]; then
-	GROUP=$USER
-fi
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 DAEMON_ARGS="-f $CONFIGFILE -P $PIDFILE $DAEMON_OPTS"
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
 
 #
 # Function that starts the daemon/service
@@ -82,10 +56,7 @@ do_start()
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
 	touch $LOGFILE && chown $USER:$GROUP $LOGFILE || return 2
-	if [ ! -d $PIDDIR ]; then
-	    mkdir $PIDDIR || return 2
-	fi
-	chown $USER:$GROUP $PIDDIR || return 2
+	mkdir -p $PIDDIR && chown $USER:$GROUP $PIDDIR || return 2
 
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
 		--chuid $USER:$GROUP --exec $DAEMON --test > /dev/null \
@@ -114,27 +85,29 @@ do_stop()
 	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
-	rm -rf $PIDDIR
+	rm -f $PIDFILE
 	return "$RETVAL"
 }
 
 #
-# Function that signals log rotation to the daemon/service
+# Function that sends a SIGUSR2 to the daemon/service
 #
 do_rotate()
 {
-	start-stop-daemon --stop --quiet --signal USR1 --pidfile $PIDFILE --exec $DAEMON
+	touch $LOGFILE && chown $USER:$GROUP $LOGFILE || return 2
+	start-stop-daemon --stop --signal USR2 --quiet --pidfile $PIDFILE --exec $DAEMON
+	return 0
 }
 
 case "$1" in
   start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
-    do_start
-    case "$?" in
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
-  ;;
+	;;
   stop)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
@@ -144,8 +117,8 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
   restart|force-reload)
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
@@ -163,16 +136,16 @@ case "$1" in
 		esac
 		;;
 	  *)
-	  	# Failed to stop
+		# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
   rotate)
-        log_daemon_msg "Reopening log file $LOGFILE"
-        do_rotate
-        log_end_msg $?
-        ;;
+	log_daemon_msg "Reopening logs for $DESC" "$NAME"
+	do_rotate
+	log_end_msg $?
+	;;
   *)
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload|rotate}" >&2
 	exit 3
